### ISSUE TITLE
RiveScript#reply is not thread-safe

### ISSUE THREAD

**Issue by UshakovVasilii** [aichaos/rivescript-java#18]
Look like RiveScript#reply is not thread-safe, RiveScript#currentUser is not ThreadLocal, project has no any synchronized blocks and concurrent classes

**Comment by kirsle** [comment]
In case I don't get around to fixing this soon, feel free to fix it and send a PR.

**Comment by marceloverdijk** [comment]
Probably best to store the username in a `ThreadLocal` and set it at start of `reply` method and retrieve it from the `ThreadLocal` in `currentUser()`.

Note this issue has only impact if you are using custom RiveScript Macros that call `rs.currentUser()`.

**Comment by marceloverdijk** [comment]
Hi @UshakovVasilii, this should be fixed in `master` now. If you need this we can make a `0.7.2` fix release and ship it to Maven. Just let me know.

**Comment by UshakovVasilii** [comment]
Hi, it is not necessary for me now. I'm using workaround.
Thank you!
