### ISSUE TITLE
that operator make wrong output

### ISSUE THREAD

**Issue by pureexe** [aichaos/rivescript-java#4]
from this rivescript
```
+ hello
- ok

% ok
+ hello
- not ok

*
- catch
```
first time i say hello it should reply ok. second time shoud say not ok. otherwise should say catch but the result is
![here is image](http://i.imghub.co/70162d9b5dc21f8c8edcba3a9f97e5fd.png)

sorry for my bad english.

**Comment by kirsle** [comment]
Try moving the % command below the line for the reply it belongs to, like this:

```
+ hello
- ok

+ hello
% ok
- not ok

*
- catch
```
