### ISSUE TITLE
Support listing of all topics

### ISSUE THREAD

**Issue by KadekM** [aichaos/rivescript-java#47]
Could we expose getter for parsed topics?
```
private Map<String, Topic> topics;                  // main topic structure
```

or something in simillar fashion? As we have for subroutines etc.

**Comment by marceloverdijk** [comment]
@KadekM what is your use case?

**Comment by KadekM** [comment]
I want to show all topic names from parsed RiveScript.

**Comment by KadekM** [comment]
Just pure RiveScript java lib - we are using it from Scala.
