### ISSUE TITLE
Multiple/Alternative Triggers

### ISSUE THREAD

**Issue by bhatmanjokes** [aichaos/rivescript-java#58]
I would like to give multiple triggers for a single response, also i would like to access the '*' within them. 
For example:
```
+ my name *
+ people call me *
+ * is what you should call me
- Ok, I will call you <star>.
```
What would be the correct way of doing this ?

**Comment by kirsle** [comment]
Maybe:

```
+ (my name is|people call me) *
- Ok, I will call you <star2>.

+ * is what you should call me
@ my name is <star>
```

**Comment by bhatmanjokes** [comment]
It is now working!!
Thank you for your timely response!!
