### ISSUE TITLE
Trouble loading files

### ISSUE THREAD

**Issue by ArjunVermaGitHub** [aichaos/rivescript-java#62]
Hey guys, thanks so much for making this framework available. I love Rivescript in terms of what it offers, but I am unable to use some rivescript files I have created in my java project and it is KILLING me. I am sure I am doing something wrong here myself, but anyway here is my problem:
I am getting file not found and directory not found exceptions whenever I try to load my rive files or directories. I have tried passing both the absolute and the relative path(I kept it relative to the java file) but to no avail. Even when the absolute path is correct, it says it isnt found. I tried changing the code up here and there but to no avail.
Here is the relevant stack:
     Caused by: com.rivescript.RiveScriptException: Directory 'replies' not found
When my code contained this:
bot.loadDirectory("replies");
        I tried making it "./replies" and I tried adding my files directly as well. But to no avail.
Can someone please help me? I feel so close yet so far and didn't know where else to go. Much thanks.

**Comment by marceloverdijk** [comment]
@ArjunVermaGitHub is there a github repo you can share?

**Comment by ArjunVermaGitHub** [comment]
I haven't really uploaded it on GitHub, but I can if that'll make it
easier. Its on Android Studio, so it'll have a lot of content

**Comment by marceloverdijk** [comment]
`bot.loadDirectory` has various methods, you can e.g. also pass an actual `java.io.File` parameter.
I think your running app cannot access the directory you specified as the error originates from https://github.com/aichaos/rivescript-java/blob/57a1274c066ad028db9af63122fc007488c082d3/rivescript-core/src/main/java/com/rivescript/RiveScript.java#L686

You could also debug the code to see what goes on.

**Comment by ArjunVermaGitHub** [comment]
The we definitely originates from there as the error message says directory
(directory) not found.
I just don't understand how to solve it. I will try passing the java.io
file. Alternatively, is it possible to put the rivescript code in without
the use of a file?

**Comment by marceloverdijk** [comment]
Yes, you could stream the RiveScript code also directly in the bot using `bot.stream(String code)`.

See https://github.com/aichaos/rivescript-java/blob/57a1274c066ad028db9af63122fc007488c082d3/rivescript-core/src/main/java/com/rivescript/RiveScript.java#L735

**Comment by ArjunVermaGitHub** [comment]
Thanks so much, for now I'm making use of this function.

**Comment by marceloverdijk** [comment]
OK thx for the feedback, closing this ticket.
