### ISSUE TITLE
Bug with sorting %Previous triggers

### ISSUE THREAD

**Issue by kirsle** [aichaos/rivescript-java#9]
From [RiveScript-JS #122](https://github.com/aichaos/rivescript-js/issues/122), ordering of triggers with a common `%Previous` are sorted incorrectly.

See the linked issue for details.

**Comment by balachandarsv** [comment]
I am not able to reproduce the bug! It is working fine in java as expected.

**Comment by marceloverdijk** [comment]
https://github.com/aichaos/rivescript-java/blob/master/rivescript-core/src/main/java/com/rivescript/Topic.java#L399

**Comment by marceloverdijk** [comment]
@kirsle I need your advise.

Do you think we can solve this by simply doing the same as https://github.com/aichaos/rivescript-java/blob/master/rivescript-core/src/main/java/com/rivescript/Topic.java#L263-L306 inside `sortPrevious()`?

**Comment by fabioravila** [comment]
@marceloverdijk I fix this on csharp lib, ytou can base on that.

See [rivescript-csharp#14](https://github.com/fabioravila/rivescript-csharp/issues/14)

**Comment by marceloverdijk** [comment]
@fabioravila thx! will have a look.
